Updated Readme - added note about maven compile target failure
confluentinc/parallel-consumer pull request #160
Opened 2021-09-09 09:30 UTC by rkolesnev

Updated Readme - added note about maven compile target failure due to a test-jar dependency resolution bug.

2021-09-09 09:42 UTC, astubbs commented
Please rebase

2021-09-09 09:43 UTC, astubbs requested changes

2021-09-09 09:43 UTC, astubbs commented on src/docs/README.adoc
> +Note::
did you make a GH issue for this to be fixed as well? If not please do so. And link to the GH issue from the note in the readme.

2021-09-09 10:51 UTC, astubbs requested changes

2021-09-09 10:51 UTC, astubbs commented on src/docs/README.adoc
> +See https://github.com/confluentinc/parallel-consumer/issues/162
```suggestion
See https://github.com/confluentinc/parallel-consumer/issues/162[issue #162]
```

2021-09-09 10:51 UTC, astubbs commented on src/docs/README.adoc
> +and https://stackoverflow.com/questions/4786881/why-is-test-jar-dependency-required-for-mvn-compile
```suggestion
and this https://stackoverflow.com/questions/4786881/why-is-test-jar-dependency-required-for-mvn-compile[Stack Overflow question].
```

2021-09-09 10:51 UTC, astubbs commented on src/docs/README.adoc
> +mvn compile - Due to a bug in maven handling of test-jar dependencies - running `mvn compile` fails,
```suggestion
`mvn compile` - Due to a bug in Maven's handling of test-jar dependencies - running `mvn compile` fails, Use `mvn test-compile` instead.
```

2021-09-10 12:26 UTC, rkolesnev commented on src/docs/README.adoc
> +mvn compile - Due to a bug in maven handling of test-jar dependencies - running `mvn compile` fails,
updated

2021-09-10 12:26 UTC, rkolesnev commented on src/docs/README.adoc
> +and https://stackoverflow.com/questions/4786881/why-is-test-jar-dependency-required-for-mvn-compile
updated.

2021-09-10 12:26 UTC, rkolesnev commented on src/docs/README.adoc
> +See https://github.com/confluentinc/parallel-consumer/issues/162
updated.

2021-09-10 12:41 UTC, astubbs approved these changes

2021-09-10 12:42 UTC, merged