feature: #242 Explicit retry exception for cleaner logging
confluentinc/parallel-consumer pull request #291
Opened 2022-05-06 12:12 UTC by astubbs

2022-05-12 12:52 UTC, astubbs commented on parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java
> +                log.debug("Explicit " + RetriableException.class.getSimpleName() + " caught, logging at DEBUG only. " + msg, e);
haha yeah good point :)

2022-05-12 13:06 UTC, astubbs commented on parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java
> +            if (e instanceof RetriableException) {
It's mostly for the common failure handling logic and message reuse.
The throw wouldn't be caught here though.

The alternative would look like:

        } catch (RetriableException e) {
            String msg = "Exception caught in user function running stage, registering WC as failed, returning to mailbox";
            log.debug("Explicit " + RetriableException.class.getSimpleName() + " caught, logging at DEBUG only. " + msg, e);
            handleFailure(workContainerBatch, e);
            throw e; // trow again to make the future failed
        } catch (Exception e) {
            log.error("Exception caught in user function running stage, registering WC as failed, returning to mailbox", e);
            handleFailure(workContainerBatch, e);
            throw e; // trow again to make the future failed
        }
    }

    private void handleFailure(final List<? extends WorkContainer<K, V>> workContainerBatch, final Exception e) {
        for (var wc : workContainerBatch) {
            wc.onUserFunctionFailure(e);
            addToMailbox(wc); // always add on error
        }
    }

2022-05-12 13:07 UTC, astubbs commented on parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java
> +            if (e instanceof RetriableException) {
let me know what you think :)

2022-05-12 16:46 UTC, astubbs commented
#268 ?

2022-05-13 11:44 UTC, ifeeneyconfluent commented on parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java
> +            if (e instanceof RetriableException) {
Ah yes, the log level param does look a nicer.  Honestly though, I prefer the explicit handler for RetriableException, but many ways to skin a cat! ;-)

2022-05-13 11:45 UTC, ifeeneyconfluent approved these changes
FWIW, I'm happy to approve.

2022-05-13 14:52 UTC, rkolesnev requested changes

2022-05-14 07:59 UTC, astubbs commented on parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java
> +                closeDontDrainFirst();
yeah, it is graceful - `closeDontDrainFirst` will commit everything that's done first - drain isn't graceful, it means process everything in buffers.
Inflight - good point, not 100% will need to double check.

2022-05-14 08:00 UTC, astubbs commented on parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java
>          }
current = retry :)

> wouldn't this just kill PC and not retry the message?

yeah there was a bug - check latest version?

2022-05-17 18:07 UTC, astubbs commented
Consider splitting the partial batch failure support into a seperate task.

2022-05-20 14:58 UTC, astubbs reviewed
...

2022-05-20 14:58 UTC, astubbs commented on parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/PCUserException.java
> + * todo
docs

2022-05-20 14:58 UTC, astubbs commented on parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/internal/UserFunctionRunnerTest.java
> +class UserFunctionRunnerTest {
finish test

2022-05-20 14:58 UTC, astubbs commented on parallel-consumer-core/src/test/resources/logback-test.xml
> +    <logger name="io.confluent.parallelconsumer" level="debug"/>
reset

2022-07-12 12:59 UTC, astubbs commented on parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/UserFunctionRunner.java
> +        }
This needs to be optional behaviour - I thought I had implemented that in this PR, but might be somewhere else. Either way, it should do like KS does - and have this be configurable.
I'll also probably copy their default behaviour.

2023-06-15 14:34 UTC, eddyv commented
Closing - Stale.

2023-06-15 14:34 UTC, closed without merging

2023-12-20 22:53 UTC, nizarsalhaji94 commented
Hi @astubbs 

Is a released date is planned ? 
I’m interested to use SHUTDOWN Terminal Failure Reatction.
In fact, we need to shutdown (or stop or kill) the PC after max retry. 

Thanks

2023-12-21 02:24 UTC, astubbs commented
@nizarsalhaji94 hi sorry I am no longer involved with this project since February 2023. Try asking @eddyv

2023-12-21 11:46 UTC, nizarsalhaji94 commented
Hi @eddyv 

Is a released date is planned ?
I’m interested to use SHUTDOWN Terminal Failure Reatction.
In fact, we need to shutdown (or stop or kill) the PC after max retry.

Thanks

2024-03-01 17:14 UTC, rkolesnev commented
@nizarsalhaji94
We are planning to implement this feature at some point, but no concrete dates / roadmap for this yet.
As a work around - i have suggested to do the stop/kill from user function approach - in this issue https://github.com/confluentinc/parallel-consumer/issues/718#issuecomment-1945771005

Just in general - i haven't seen your comment here until now - in the future - it would be more visible if you raise it as a question / issue with link to the PR if its relevant.