improves: Error in onPartitionsAssigned in parallel consumer
confluentinc/parallel-consumer pull request #537
Opened 2023-01-13 22:18 UTC by nachomdo

Improves: https://github.com/confluentinc/parallel-consumer/issues/326 

Adds an option to pass an invalid offset metadata error policy in case of accidentally or deliberately reusing a Kafka Streams consumer group. The default policy is to fail and stop the execution. 

### Checklist

- [] Documentation (if applicable)
- [] Changelog

2023-01-13 22:22 UTC, nachomdo commented on parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/offsets/OffsetMapCodecManager.java
> +        this.errorPolicy = module.options().getInvalidOffsetMetadataPolicy();
Not my favourite option this mixture of static and instance scope 😢

2023-06-20 19:22 UTC, eddyv requested changes
Add one more test and LGTM.

2023-06-20 19:22 UTC, eddyv commented on parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/offsets/WorkManagerOffsetMapCodecManagerTest.java
Should probably add a test for `deserialiseKafkaStreamsV2WithIgnoreErrorPolicy `

2023-07-10 10:41 UTC, nachomdo commented on parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/offsets/WorkManagerOffsetMapCodecManagerTest.java
Thanks for the review @eddyv 🙇‍♂️  I've added the suggested test

2023-07-17 20:54 UTC, eddyv approved these changes
Lgtm

2023-07-17 20:55 UTC, merged