Ehud lev add min batch size
confluentinc/parallel-consumer pull request #562
Opened 2023-03-03 10:40 UTC by Ehud-Lev-Forter

Description...
We would like to support minimum batch size. Since we might have a time with no traffic and we don't want to wait forever for the events that are not satisfy minimum batch, we will also add `minBatchTimeoutInMillis`, if we passed this timeout, code will be as today.
[see issue](https://github.com/confluentinc/parallel-consumer/issues/560)

### Checklist

- [ ] Documentation (if applicable)
- [ ] Changelog

2023-03-03 10:50 UTC, astubbs commented
Title should be something likes:

feature: Add min batch size support

2023-05-26 08:47 UTC, rkolesnev requested changes
In general logical flow looks fine to me.
I would really like to see more tests and integration tests for it though - with transactions, different ordering modes (Unordered / Key /Partition) and 'normal' non-reactor usage mode of PC - it has a potential to introduce edge case issues that additional tests could shake out.

2023-06-20 18:39 UTC, eddyv reviewed
Seems to break a test 

```
[ERROR] io.confluent.parallelconsumer.state.WorkManagerTest.resumesFromNextShard(ProcessingOrder)[1] -- Time elapsed: 0.007 s <<< FAILURE!
14:36:51  expected: 1
14:36:51  but was : 2
```

2023-06-20 18:39 UTC, eddyv commented on parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/ParallelConsumerOptions.java
> +                        msg("minBatchSize can not by bigger than batchSize: {} > {}",
```suggestion
                        msg("minBatchSize cannot be bigger than batchSize: {} > {}",
```
typo

2023-11-03 18:14 UTC, closed without merging