Fix for race condition in partition state clean/dirty tracking
confluentinc/parallel-consumer pull request #666
Opened 2023-11-17 14:04 UTC by rkolesnev

Fix for race condition in partition state clean/dirty tracking - see #664 
### Checklist

- [X] Documentation (if applicable)
- [X] Changelog

2023-11-17 14:12 UTC, eddyv approved these changes
small nitpick

2023-11-17 14:12 UTC, eddyv commented on parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/PartitionState.java
> +        }
nitpick
```suggestion
        }
        return empty();
```

2023-11-17 18:28 UTC, eddyv requested changes
```
09:12:18  [ERROR] /home/jenkins/workspace/builder_parallel-consumer_PR-666/parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/state/PartitionStateCommittedOffsetTest.java:[185,137] cannot find symbol
09:12:18  [ERROR]   symbol:   method of(long,long)
09:12:18  [ERROR]   location: interface java.util.List
```
Missing something 😅

2023-11-20 10:01 UTC, rkolesnev commented
> ```
> 09:12:18  [ERROR] /home/jenkins/workspace/builder_parallel-consumer_PR-666/parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/state/PartitionStateCommittedOffsetTest.java:[185,137] cannot find symbol
> 09:12:18  [ERROR]   symbol:   method of(long,long)
> 09:12:18  [ERROR]   location: interface java.util.List
> ```
> 
> Missing something 😅

Ah - local build on newer java... while CI build on java 8 i think - which ofc doesn't have List.of(...) support

2023-11-20 10:14 UTC, rkolesnev commented on parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/PartitionState.java
> +        }
done

2023-11-20 13:54 UTC, eddyv approved these changes

2023-11-20 15:32 UTC, merged