Kafka 3.7.0 fixes
confluentinc/parallel-consumer pull request #746
Opened 2024-03-30 20:39 UTC by ondryaso

This is the bare minimum to make the library work with version 3.7.0 of the Kafka client. It fixes the bug reported in #721 and also introduces the option, mentioned therein, to disable the auto commit check (by making it "soft", i.e. not throwing an exception).

### Checklist

- [ ] Documentation (if applicable)
- [ ] Changelog

2024-04-02 13:49 UTC, rkolesnev requested changes
Overall looks good. 
I have left some comments - mainly to make the new flag more explicit in that it only allows to suppress reflective access errors - not disable the auto commit check itself.
I dont see any reason to disable auto commit check - apart from failures to actually perform the check.

Another small thing - can you please update the Changelog and regenerate Readme - to regenerate readme either run the maven target in IDE `README` or `mvn asciidoc-template:build` - ignore errors on submodules - as readme is only on top level - it reports missing template on submodules as errors.

2024-04-02 13:49 UTC, rkolesnev commented on parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/ParallelConsumerOptions.java
> +    public final boolean softAutoCommitDisabledCheck = false;
I think the name can be more explicit.
```suggestion
    public final boolean ignoreReflectiveAccessExceptionsForAutoCommitDisabledCheck = false;
```

2024-04-02 13:49 UTC, rkolesnev commented on parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/ParallelConsumerOptions.java
> +     * <code>enable.auto.commit</code> must always be disabled in your consumer.
```suggestion
     * The purpose of the flag is to be a last resort / temporary work-around for changes introduced in newer Kafka
     * Clients that break reflective access and for using wrapped, custom or extended KafkaConsumer classes that fail
     * reflection checks - setting the flag to true will ignore reflection access exceptions during this check.
     * <p>
     * Note: that library will still try to access auto commit field on the consumer object and if it is accessible and
     * not disabled - the Parallel Consumer will shut down.
```

2024-04-02 13:49 UTC, rkolesnev commented on parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java
> +                }
Revert this check back - only disabling error on reflective access - if auto commit field is accessible / found - and is not disabled - shut down with an error.
```suggestion
                if (TRUE.equals(isAutoCommitEnabled))
                    throw new ParallelConsumerException("Consumer auto commit must be disabled, as commits are handled by the library.");
```

2024-04-02 13:49 UTC, rkolesnev commented on parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java
> +                    isAutoCommitEnabled = false;
Check the new option flag and either throw an error or log a warning depending on how that flag is set - something like below:
```suggestion
               if (options.ignoreReflectiveAccessExceptionsForAutoCommitDisabledCheck()) {
                    log.warn("Consumer delegate is neither a LegacyKafkaConsumer nor a AsyncKafkaConsumer - cannot check auto commit is disabled for consumer type: {}. Ignoring due to the option flag ignoreReflectiveAccessExceptionsForAutoCommitDisabledCheck=true", consumer.getClass().getName());
                } else {
                    throw new ParallelConsumerException("Consumer delegate is neither a LegacyKafkaConsumer nor a AsyncKafkaConsumer - cannot check auto commit is disabled for consumer type: " + consumer.getClass().getName());
                }
```

2024-04-02 13:49 UTC, rkolesnev commented on parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java
> +                log.error("Cannot check auto commit is disabled for consumer type: " + consumer.getClass().getName(), e);
add flag name to make it clear that its only allowed due to the explicit override flag:
```suggestion
                log.error("Cannot check auto commit is disabled for consumer type: {},  Ignoring due to the option flag ignoreReflectiveAccessExceptionsForAutoCommitDisabledCheck=true", consumer.getClass().getName(), e);
```

2024-04-16 10:39 UTC, nscuro commented
Hey @ondryaso, thanks so much for taking this up! Are you planning to address the requested changes?

I can try picking up from here in case other commitments prevent you from continuing :)

2024-04-16 11:30 UTC, ondryaso commented
@nscuro Hey, that would be awesome, I am currently totally out of time...

2024-05-03 18:38 UTC, nscuro commented
With a bit of a delay, I now raised #762 as a replacement for this PR. Thanks for your work @ondryaso, I think you can close this one.

2024-05-03 19:02 UTC, ondryaso commented
Thanks, @nscuro, closing this PR.

2024-05-03 19:02 UTC, closed without merging